---
- id: add-msg-issue
  name: Add issue to the commit message
  description: Searches the branch name for something looking like a jira issue
    name and inserts it into the commit message.
  entry: add-msg-issue
  language: python
  always_run: true
  stages: [prepare-commit-msg]
- id: strict-tdd
  name: StrictTDD
  description: Enforce strict TDD workflow
  entry: strict-tdd
  language: python
  always_run: true
  stages: commit
  pass_filename: true
