---
- id: add-msg-issue
  name: Add issue to the commit message
  description: Searches the branch name for something looking like a jira issue
    name and inserts it into the commit message.
  entry: add-msg-issue
  language: python
  always_run: true
  stages: [prepare-commit-msg]
- id: add-copyright
  name: Add copyright string to source files
  description: Checks that source files have copyright strings. Adds the string
    if necessary.
  entry: add-copyright
  language: python
  always_run: true
  stages: [commit]
  types_or:
    - c++
    - c#
    - css
    - dart
    - html
    - java
    - javascript
    - kotlin
    - lua
    - markdown
    - perl
    - php
    - python
    - ruby
    - rust
    - scala
    - sql
    - swift
- id: update-copyright
  name: Update dates on copyright strings in source files
  description: Parses copyright strings in source files, updating the date to the
    current year.
  entry: update-copyright
  language: python
  always_run: true
  stages: [commit]
  types_or:
    - c++
    - c#
    - css
    - dart
    - html
    - java
    - javascript
    - kotlin
    - lua
    - markdown
    - perl
    - php
    - python
    - ruby
    - rust
    - scala
    - sql
    - swift
- id: sort-file-contents
  name: Sort gitignore sections
  description: Sorts the contents of .gitignore while preserving sections.
  entry: sort-file-contents
  language: python
  always_run: true
  stages: [commit]
  files: ^.gitignore
- id: no-import-testtools-in-src
  name: Detect test tool imports in src files
  description: Detect test tool imports outside of test files.
  entry: no-import-testtools-in-src
  language: python
  always_run: true
  stages: [commit]
  types_or: [python]
