---
- id: add-msg-issue
  name: Add issue to the commit message
  description: Searches the branch name for something looking like a jira issue
    name and inserts it into the commit message.
  entry: add-msg-issue
  language: python
  always_run: true
  stages: [prepare-commit-msg]
- id: add-copyright
  name: Add copyright string to source files
  description: Checks that source files have copyright strings. Adds the string
    if necessary.
  entry: add-copyright
  language: python
  always_run: true
  stages: [commit]
  types_or: [python, markdown, c++, c#, perl]
- id: sort-file-contents
  name: Sort gitignore sections
  description: Sorts the contents of .gitignore while preserving sections.
  entry: sort-file-contents
  language: python
  always_run: true
  stages: [commit]
  files: ^.gitignore
- id: Check CHANGELOG clashes
  name: Check for clashes in CHANGELOG vs main.
  description: If the CHANGELOG has been modified, checks it against the current
    state of origin/main and reports any inconsistencies that indicate an outdated
    CHANGELOG.
  entry: check-changelog-clash
  language: python
  always_run: true
  stages: [push, commit]
  files: ^CHANGELOG.md
